Update summary_subgroup.R
jaredhuling/personalized pull request #3
Opened 2017-08-09 17:21 UTC by AaronPotvien

Made the following changes:
1) Added the denominator to the number of variables selected in the description (e.g. m out of n variables selected by the lasso).
2) Subtracted 2 to remove the treatment effect and intercept from the calculations in 1), as one might argue that the treatment effect is not "selected" by the lasso. Even though Intercept = F in the models, it is still present in est.coef.
3) Removed "if length(sel.idx) > 0" condition. Since Trt is always estimated, this condition appeared to be tautologically true. If treatment is the only variable present, it will just say that 0 variables out of X were selected but still should proceed to printing the treatment effect anyway.
4) This may need to be better generalized if the user intends to specify penalty.factor in the call to fit.subgroup().

2017-08-09 19:57 UTC, jaredhuling requested changes
Only 1 should be subtracted in lines 30 and 32 as there is no intercept

2017-08-09 20:19 UTC, AaronPotvien commented
It is true that there are no intercepts in these models, but in cv.glmnet(), it appears that the intercept term still takes up a slot even when the intercept flag is set to F, so this can still inflate the vector length.

#### e.g. 5 variables, but an end length of 6
```
test.fit <- cv.glmnet(x=matrix(rnorm(1000),nrow=200,ncol=5), 
                      y=rep(0:1,100),
                      intercept = F)

est.coef <- predict(test.fit, type = "coef", s = "lambda.min")
which(row.names(est.coef) == "(Intercept)")
length(est.coef)
```

2017-08-09 20:23 UTC, jaredhuling commented
That is correct, however, the the code about in summary_subgroup.R is:

`est.coef <- predict(object$model, type = "coef", s = "lambda.min")
 vnames   <- rownames(est.coef)
 est.coef <- as.vector(est.coef)
 sel.idx  <- which(est.coef != 0)`

and hence the length of `sel.idx` should be the length of the number of variables selected plus the intercept (since glmnet pads the coefficient vector with a `0` for the intercept if it is set to `FALSE`)

2017-08-09 20:57 UTC, AaronPotvien commented
How does the Trt effect come into play here?

My understanding was that `est.coef`, or more specifically, `matrix(est.coef, ncol = 1)`, takes the ordered form:

1. (Intercept - Always identically 0, not selected)
2. (Trt - Not penalized, always selected)
3. (Remaining variables eligible for selection - May or may not be selected)

2017-08-09 21:33 UTC, jaredhuling commented
That is correct, however when we filter based on which coefficients are zero, the intercept will always be absent from `sel.idx`. So the estimated treatment effect will always correspond to the first element in `sel.idx`

2017-08-10 15:35 UTC, AaronPotvien commented
Ok, that makes sense. A simple check can be to see whether `length(est.coef)-1` ultimately resolves to `ncol(x)` for the `x` passed to `fit.subgroup()`. If so, then it does correctly reflect the number of selection-eligible variables input by the user.

2017-08-10 17:18 UTC, merged